### ISSUE TITLE
Example for making this work with new yaml syntax

### ISSUE THREAD

**Issue by bfelbo** [vsoch/pull-request-action#10]
Hi. This action used to work fine before Github migrated to the new yaml syntax. Do you have an example of how to get it to work?

This is what I tried (inside `.github/workflows/auto-pull-request.yml`):
```
name: Pull Request on Branch Push
on:
  push:
    branches-ignore:
      - staging
      - launchpad
      - production
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

However, the action fails with:
```
You must include the GITHUB_TOKEN as an environment variable.
##[error]Docker run failed with exit code 1
```
