### ISSUE TITLE
Create a PR from a branch that was just merged to master

### ISSUE THREAD

**Issue by Trancever** [vsoch/pull-request-action#31]
Hey. Is it possible to use this action to open a PR from a branch "A" to branch "B" when branch "A" is merged to master?

That's what I have right now: 

```
name: Pull Request on Branch Push
on:
  push:
    branches:
      - gh-action-test
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: ""
          PULL_REQUEST_BRANCH: "4.0"
```

It opens a PR from "gh-action-test" to "4.0" whenever something is merged to "gh-action-test". I want it to open a PR from "B" to "4.0" whenever "B" is merged to "gh-action-test". Unfortunately, I have no idea how could I implement it.
