### ISSUE TITLE
Environment Variable Inputs bug

### ISSUE THREAD

**Issue by brandon-kyle-bailey** [vsoch/pull-request-action#32]
Hi, 

Have an issue that im not sure how to approach for a solution. 

problem:
- environment variable inputs either not being set, or being set incorrectly on PR creation.

example:
- [Example PR with problem](https://github.com/brandon-kyle-bailey/pandemic-observer-backend/pull/55)

code:
```
 name: Pull Request to Production on Push to Development branch
 
 on:
     push:
         branches:
             - development
 
 jobs:
   auto-pull-request:
     name: Auto Pull Request to Master
     runs-on: ubuntu-latest
     steps:
       - name: pull-request-action
         uses: vsoch/pull-request-action@1.0.5
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           PULL_REQUEST_TITLE: ${{github.event.head_commit.message}}
           PULL_REQUEST_ASSIGNEES: ${{github.event.head_commit.author.name}}
```

- the title variable seems to pick up extra information in the commit message.
- the assignees variables doesn't assign any specified users to the PR.

I have tried setting the assignees manually with:
```
           PULL_REQUEST_ASSIGNEES: "brandon-kyle-bailey"
```

to no avail. 

Does anyone have any ideas?

Thanks,

**Comment by vsoch** [comment]
hey @brandon-kyle-bailey - I'd be happy to help you with this! Let's walk through each component one step at a time.

 - version: looks like you are using 1.0.5, which is the latest that supports assignees, so we are good there
 
We can look at output for the action to see what variables it is seeing:

![image](https://user-images.githubusercontent.com/814322/79898448-84077300-83c8-11ea-841d-1d6b99352d23.png)

In the above I see that the pull request title is set to [this commit](https://github.com/brandon-kyle-bailey/pandemic-observer-backend/commit/0953f772d402e3c7b8a0e9c44d494da0b09d2f8c) 

```
Pull request title is Merge pull request #54 from brandon-kyle-bailey/issue#37
```

And for the assignee, I see:

```
PULL_REQUEST_ASSIGNEES is set, Brandon
```

So from the above I'd say that your Title is working correctly, but for assignee you are using your GitHub "name" and not the "login" (if I remember correctly). Could you find the page where the payload is described and verify what field has the username? You would need to change this line:

```
          PULL_REQUEST_ASSIGNEES: ${{github.event.head_commit.author.name}}
```
to something else. I don't remember off the top of my head, but I'd use something like sender.login.
A nice approach for debugging like this is to add a step where you can print additional variables you are interested in (if the action doesn't do it for you, which this one does.)

```yaml
    steps:
      - name: pull-request-action
        env:
          PULL_REQUEST_TITLE: ${{github.event.head_commit.message}}
          PULL_REQUEST_ASSIGNEES: ${{github.event.head_commit.author.name}}
        runs: |
            echo "${PULL_REQUEST_TITLE}"   
            echo "${PULL_REQUEST_ASSIGNEES}"   
```

So that should be enough I think for you to at least get started. If you would like to do a test run and echo those variables, and then direct me to the Action output where they are printed (and the action fails) I'd be happy to take a look. Also keep in mind that assignees and reviewers need to have admin on the repo, or be someone that you could assign manually in the interface (all other cases are ignored).
