### ISSUE TITLE
Cannot index string with string "head"

### ISSUE THREAD

**Issue by ALefaux** [vsoch/pull-request-action#35]
Hi! 
I started using your actions two weeks ago and all works fine.
I modified some code for my PR and the actions doesn't work with this error :
```
Enter host password for user 'ALefaux':
jq: error (at <stdin>:4): Cannot index string with string "head"
```

**Comment by vsoch** [comment]
Could you please share the "code you modified for your PR" and enough to reproduce your error?

**Comment by ALefaux** [comment]
```
name: Open pull request after push

on:
  push:
    branches:
      - '*/*'

jobs:
  open-pull-request:
    name: Open the pull request
    runs-on: ubuntu-latest

    steps:
      - name: open-pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "master"
          PULL_REQUEST_ASSIGNEES: "ALefaux"
```
