### ISSUE TITLE
Add ability to set pull request author to the person who pushed

### ISSUE THREAD

**Issue by EvgenyOrekhov** [vsoch/pull-request-action#36]
PRs created by pull-request-action set PR author to @github-actions bot, which messes up our stats in Code Climate Velocity.

We would like the PR author to be the person who pushed the branch.

I tried to do this:

```yaml
steps:
  - uses: vsoch/pull-request-action@1.0.6

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.event.pusher.name }}
```

but it didn't work.

**Comment by vsoch** [comment]
Can you show me a link to a test run so I can see what you are trying to do?

**Comment by EvgenyOrekhov** [comment]
It's in a private repo.

Here is our workflow:

```yaml
name: PR
on:
  push:
    branches-ignore:
      - master
jobs:
  auto-pull-request:
    name: Create PR on branch push
    runs-on: ubuntu-latest
    steps:
      - uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: master
          PULL_REQUEST_DRAFT: true
```

The problem is with the author of PRs:

![image](https://user-images.githubusercontent.com/8045060/87179809-04fb4a00-c2e8-11ea-934c-00cb6a246a95.png)

We want it to be the person who pushed the branch, not github-actions bot.
