### ISSUE TITLE
New pull requests that can be created with v1.0.8 are not created with v1.0.9

### ISSUE THREAD

**Issue by cbruno10** [vsoch/pull-request-action#45]
We recently switched our workflow to use the latest version, 1.0.9, for this action but noticed that the action wasn't creating the pull request for a branch that didn't have a pull request yet, even though the action itself was not failing.

Usage:
```
      - name: Create pull request
        id: create-pull-request
        if: steps.find-pull-request.outputs.number == ''
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_TITLE: ${{ steps.pr-text.outputs.title }}
          PULL_REQUEST_BODY: ${{ steps.pr-text.outputs.body }}
```

When looking in the workflow logs, we get the following output:
```
START: Running Pull Request on Branch Update Action!
Found ${GITHUB_EVENT_PATH} at /github/workflow/event.json
Branch prefix is 
No branch prefix is set, all branches will be used.
Pull requests will go to master
No explicit preference for draft PR: created PRs will be normal PRs.
No explicit preference for maintainer being able to modify: default is true.
PULL_REQUEST_ASSIGNEES is not set, no assignees.
PULL_REQUEST_REVIEWERS is not set, no reviewers.
PULL_REQUEST_TEAM_REVIEWERS is not set, no team reviewers.
PULL_REQUEST_FROM_BRANCH is not set, checking branch in payload.
Found ${GITHUB_EVENT_PATH} at /github/workflow/event.json
Found branch wip/azure-dns/epic-noether to open PR from
Pull request body is 
# 1.1.0 (2020-09-25)

- Minor improvements

# 1.0.0 (2020-05-12)

- Initial release

Pull request title is Mod release candidate for azure-dns 1.2.0

Data for checking if pull request exists: {'base': 'master', 'head': 'wip/azure-dns/epic-noether', 'body': "\n# 1.1.0 (2020-09-25)\n\n- Minor improvements# 1.0.0 (2020-05-12)\n\n- Initial release"}

github pr response
<truncated JSON response due to length>
==========================================================================
END: Finished
```

I can see that it reaches the `github pr response`, but finishes immediately after. In the log for the `github pr response`, it has 11k+ lines of JSON data, containing information about currently open PRs in our repo, though none of them are relevant to this branch.

Is there something we have to change when calling the action in 1.0.9?

**Comment by cbruno10** [comment]
Also, after getting the output above, we tested running this action with the same inputs, just pinning it to 1.0.8, and that run was able to successfully create a new PR for the branch, with log messages showing up for the groups `github pr response`, `github response`, and a closing success message of "Number opened for PR is 28811".

**Comment by vsoch** [comment]
hey @cbruno10 ! The difference between 1.08 and 1.0.9 is a refactor from bash to python, namely because users were having issues with debugging and python can better show the logging. In the meantime, if there is a version that works for you, you should use that, and let's see if we can work together to debug the issues with 1.0.9. Could you please share with me the response to the initial query (or point me to the gitHub url) so I can debug, and prepare a branch for you to test? I'd like to get everything working as expected with the latest Python version.

**Comment by vsoch** [comment]
okay I've created an `update/python-client` branch that instead of printing the entire response, looks at the first head ref - which I think should emulate the previous bash, if you are able to test!

**Comment by vsoch** [comment]
hey again! I've gone through testing of the branch, and it works as I'd expect now, if you'd like to test! The issue was just printing the entire response (for all branches) when we needed to search. I'm not sure if the GitHub API has changed, but it should have been the case that we didn't get back all PRs for the repo. It's not a big deal because we can just loop and look for the branch we want to open. Here are the logs of the run that I just did, https://github.com/vsoch/pull-request-action-example/runs/1167820772?check_suite_focus=true and it would be great if you can test too! If all looks good we can do a quick release. I also don't think it's intuitive for the default to not fail, so I switched around the variable to require the user to set `PASS_ON_FAIL` and then it would fail by default. Sorry for the trouble!

**Comment by cbruno10** [comment]
Thank you for the quick response and testing @vsoch ! I should have a chance later today to test it out and I'll let you know the results.

**Comment by vsoch** [comment]
Awesome! Thank you so much. I'm wanting to get the latest back up and working as expected, and really appreciate the help.

**Comment by cbruno10** [comment]
@vsoch I just ran the same workflow with the updated branch:
```
      - name: Create pull request
        id: create-pull-request
        if: steps.find-pull-request.outputs.number == ''
        uses: vsoch/pull-request-action@update/python-client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_TITLE: ${{ steps.pr-text.outputs.title }}
          PULL_REQUEST_BODY: ${{ steps.pr-text.outputs.body }}
```

Unfortunately, the pull request was not created and the action did not fail, here are the logs:
```
==========================================================================
START: Running Pull Request on Branch Update Action!
Found ${GITHUB_EVENT_PATH} at /github/workflow/event.json
Branch prefix is 
No branch prefix is set, all branches will be used.
Pull requests will go to master
No explicit preference for draft PR: created PRs will be normal PRs.
No explicit preference for maintainer being able to modify: default is true.
PULL_REQUEST_ASSIGNEES is not set, no assignees.
PULL_REQUEST_REVIEWERS is not set, no reviewers.
PULL_REQUEST_TEAM_REVIEWERS is not set, no team reviewers.
PULL_REQUEST_FROM_BRANCH is not set, checking branch in payload.
Found ${GITHUB_EVENT_PATH} at /github/workflow/event.json
Found branch wip/aws-acm/peaceful-kowalevski to open PR from
Pull request body is 
<body truncated, similar to the one in the original comment though>
==========================================================================
END: Finished
```

This is also in a private repo, so apologies for not being able to link to the actual workflow run.

Please let me know if there's anything else you need from me.
