### ISSUE TITLE
Feature request: PR title variable, default PR title

### ISSUE THREAD

**Issue by AnandChowdhary** [vsoch/pull-request-action#47]
This is a feature request, not very high priority, and totally up to your discretion if you want to implement it. 👍

Currently, the default PR title is "Update from branch-name" where `branch-name` is the name of the branch.

**Feature request 1:** Support for having the variable `$BRANCH_NAME` in the PR title:

```yaml
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          PULL_REQUEST_TITLE: "This is an update from $BRANCH_NAME"
```

In the above example, `$BRANCH_NAME` will be automatically replaced with the name of the branch. This way, we can customize the PR title, including the branch name in it as well.

**Feature request 2:** Change the default PR title from "Update from branch-name" to "Branch name"

If you open a new PR using the GitHub UI, the default PR title is a sentence-case version of the branch name. For example, a branch called "new-interface-for-admin" will have the default PR title "New interface for admin". The rules are that all hyphens are converted to spaces and the first letter is capitalized.

I'd love it if we can, consistently with the GitHub UI, have that as the default PR title. In our use case, "Branch name" gives the info a lot clearer than "Update from branch-name".

**Comment by vsoch** [comment]
hey @AnandChowdhary ! Some quick good news is that we don't need to hard code variables into other variables because you can easily do this with GitHub actions. For example:

> Feature request 1: Support for having the variable $BRANCH_NAME in the PR title:

For the above, you can just have a previous step that formats the branch name into whatever you like!

```yaml
          echo "::set-env name=PULL_REQUEST_FROM_BRANCH::${BRANCH_FROM}"
    - name: Open Pull Request
      uses: vsoch/pull-request-action@1.0.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: "master"
```

In the above, the branch for the action is set in the previous action from an envar that I've created. You can also use one from GitHub's [predefined set](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables). You can also reference the outputs / steps from other actions directly, e.g., see the variables [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions) and take a look in the examples folder for a few files.

> Feature request 2: Change the default PR title from "Update from branch-name" to "Branch name"

This would be a reasonable request - but I think I'd want to ensure that there is some label to indicate it's automated / opened from a bot. What about testing "[pull-request-action] Branch name"? And how would we deal with slashes? Let's leave this issue open, and see if we can get more users +1'ing this request. If there is enough agreement about the change then I'd be happy to review a PR (with a matching example test that shows it working). Cheers!
