### ISSUE TITLE
Allow to open PR in another repository

### ISSUE THREAD

**Issue by fbiville** [vsoch/pull-request-action#76]

**Comment by vsoch** [comment]
You should be able to do this, but you’ll need to use a personal access token.

**Comment by fbiville** [comment]
Thanks for your quick reply!
So if I've got repo A, branch X, I can already open PRs against repo B targeting branch Y?
How does the configuration look like in that case? I could not figure out.

**Comment by vsoch** [comment]
Use the environment variable PULL_REQUEST_REPOSITORY. Did you look at the README at all? https://github.com/vsoch/pull-request-action

**Comment by fbiville** [comment]
Yes I did, and I tried it without success. But thanks for assuming otherwise.

Anyway, after reviewing GitHub API docs, I might be able to make it work with a combination of `PULL_REQUEST_FROM_BRANCH` (with the qualified branch name: `user:branch` and `PULL_REQUEST_REPOSITORY`.

This use case would be worth documenting in your README.

**Comment by fbiville** [comment]
I managed to make it work 🥳 

Here is the pipeline I set up on the source repo (`fbiville/commit-fwd-source-repo`):
```yaml
name: Commit forward
on:
  push:
    branches: ['4.3']
jobs:
  commit-forward:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.FORWARD_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: "fbiville:4.3"
          PULL_REQUEST_BRANCH: "4.3"
          PULL_REQUEST_REPOSITORY: fbiville-testing/commit-fwd-source-repo
```

This forwards every commit from the 4.3 branch of fbiville/commit-fwd-source-repo to the 4.3 branch of `fbiville-testing/commit-fwd-source-repo`.
Note that it required an explicit user-defined personal token for it to work
