### ISSUE TITLE
Add retry for opening PR

### ISSUE THREAD

**Issue by vsoch** [vsoch/pull-request-action#95]
Arguably, we would get around a lot of the rate limiting issues if we add a simple retry! I can work on this soon.

**Comment by vsoch** [comment]
If anyone wants to test this on their repos, please use this branch: https://github.com/vsoch/pull-request-action/pull/96

```yaml
- name: Open Pull Request
      uses: vsoch/pull-request-action@add/retry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: "main"
```
I'm adding to some of my repos that have failed due to rate limits to see if it makes a difference, and if the defaults I've set are reasonable.
